services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api_endpoints.json:/app/api_endpoints.json
      - ./gradio_auth:/app/gradio_auth
      - /var/log/fschat:/log
    working_dir: /log
    environment:
      TZ: Asia/Tokyo
    networks:
      - litellm_shared
      - default 
    command:
      - -m
      - fastchat.serve.gradio_web_server_multi
      - --host
      - '0.0.0.0'
      - --port
      - '8080'
      - --controller-url
      - ''
      - --register-api-endpoint-file
      - /app/api_endpoints.json
      - --gradio-auth-path
      - /app/gradio_auth
      - --show-terms-of-use
      - --concurrency-count
      - '20'
    
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./caddy/.env
    cap_add:
      - NET_ADMIN
    ports:
      - '443:443'
      - '443:443/udp'
    networks:
      - default
      - litellm_shared
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/flags:/flags

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  litellm_shared:
    external: true
