services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api_endpoints.json:/app/api_endpoints.json
      - ./gradio_auth:/app/gradio_auth
      - /var/log/fschat:/log
    working_dir: /log
    environment:
      - TZ=Asia/Tokyo
    networks:
      - fastchat_litellm
      - caddy_fastchat
    command:
      - -m
      - fastchat.serve.gradio_web_server_multi
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --controller-url
      - ''
      - --register-api-endpoint-file
      - /app/api_endpoints.json
      - --gradio-auth-path
      - /app/gradio_auth
    
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./caddy/.env
    cap_add:
      - NET_ADMIN
    ports:
      - '443:443'
      - '443:443/udp'
    networks:
      - caddy_fastchat
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  caddy_fastchat:
  fastchat_litellm:
    external: true
