services:
  controller:
    container_name: controller
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - -m
      - fastchat.serve.controller
      - --host
      - 0.0.0.0
      - --port
      - '3000'

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - controller
    volumes:
      - ./api_endpoints.json:/app/api_endpoints.json
      - ./gradio_auth:/app/gradio_auth
      - /var/log/fschat:/log
    working_dir: /log
    command:
      - -m
      - fastchat.serve.gradio_web_server_multi
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --controller-url
      - http://controller:3000
      - --register-api-endpoint-file
      - /app/api_endpoints.json
      - --gradio-auth-path
      - /app/gradio_auth
    
  caddy:
    container_name: caddy
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    env_file:
      - ./caddy/.env
    cap_add:
      - NET_ADMIN
    ports:
      - '443:443'
      - '443:443/udp'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
    external: true
  caddy_config:
