# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

tasks:
  replace-api-key:
    desc: Replace API key in api_endpoints.json
    preconditions:
      - test -f api_endpoints.json
      - test -n "{{.CLI_ARGS}}"
    cmds:
      - |
        jq --arg new_key "{{.CLI_ARGS}}" '
          walk(
            if type == "object" and has("api_key") then 
              .api_key = $new_key 
            else 
              . 
            end
          )
        ' api_endpoints.json > api_endpoints.json.tmp
      - mv api_endpoints.json.tmp api_endpoints.json

  configure-docker:
    desc: Create external volumes and networks
    cmds:
      - docker volume create caddy_data
      - docker network create litellm_shared
    status:
      - docker volume inspect caddy_data
      - docker network inspect litellm_shared

  clean:
    desc: Clean up
    prompt: Are you sure you want to clean up?
    cmds:
      - rm -f api_endpoints.json
      - docker volume rm caddy_data
      - docker network rm litellm_shared
    status:
      - test ! -f api_endpoints.json
      - docker volume inspect caddy_data || true
      - docker network inspect litellm_shared || true
