# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: '3'

vars:
  MODELS:
    meta-llama/Meta-Llama-3-8B-Instruct
    cyberagent/calm3-22b-chat
    elyza/Llama-3-ELYZA-JP-8B
    llm-jp/llm-jp-13b-instruct-full-ac_001_16x-dolly-ichikara_004_001_single-oasst-oasst2-v2.0
    tokyotech-llm/Llama-3-Swallow-8B-Instruct-v0.1
    tokyotech-llm/Swallow-MS-7b-instruct-v0.1
    tokyotech-llm/Swallow-MX-8x7b-NVE-v0.1
    tokyotech-llm/Llama-3-Swallow-70B-Instruct-v0.1

tasks:
  replace-api-key:
    desc: Replace API key in api_endpoints.json
    preconditions:
      - test -f api_endpoints.json
      - test -n "{{.CLI_ARGS}}"
    cmds:
      - |
        jq --arg new_key "{{.CLI_ARGS}}" '
          walk(
            if type == "object" and has("api_key") then 
              .api_key = $new_key 
            else 
              . 
            end
          )
        ' api_endpoints.json > api_endpoints.json.tmp
      - mv api_endpoints.json.tmp api_endpoints.json

  configure-docker:
    desc: Create external volumes and networks
    cmds:
      - docker volume create caddy_data
      - docker network create litellm_shared
    status:
      - docker volume inspect caddy_data
      - docker network inspect litellm_shared

  clean:
    desc: Clean up
    prompt: Are you sure you want to clean up?
    cmds:
      - rm -f api_endpoints.json
      - docker volume rm caddy_data
      - docker network rm litellm_shared
    status:
      - test ! -f api_endpoints.json
      - docker volume inspect caddy_data || true
      - docker network inspect litellm_shared || true