AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet 2
  FastChatECRRepositoryName:
    Type: String
    Description: ECR Repository name for FastChat
  ControllerSGID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Controller Security Group
  GradioSGID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Gradio Security Group
  ControllerTargetGroupArn:
    Type: String
    Description: The ARN of the Controller Target Group
  GradioTargetGroupArn:
    Type: String
    Description: The ARN of the Gradio Target Group
  ControllerLoadBalancerDNSName:
    Type: String
    Description: The DNS Name of the Controller Load Balancer

Resources:
  ### Common ###
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "cluster-${AWS::StackName}"

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "log-group-${AWS::StackName}"
      RetentionInDays: 5

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ECSTaskExecutionRole-chatbot-arena
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ### Task Definition ###
  ControllerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "controller-task-${AWS::StackName}"
      RequiresCompatibilities:
        - FARGATE
      Cpu: 4096 # 4 vCPU
      Memory: 8192 # 8 GB
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: fastchat-controller
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FastChatECRRepositoryName}:latest"
          Essential: true
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: TZ
              Value: Asia/Tokyo
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: controller
          Command: ["-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "3000"]

  GradioTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "gradio-task-${AWS::StackName}"
      RequiresCompatibilities:
        - FARGATE
      Cpu: 4096 # 4 vCPU
      Memory: 8192 # 8 GB
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: fastchat-gradio
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FastChatECRRepositoryName}:latest"
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: TZ
              Value: Asia/Tokyo
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: gradio
          Command: ["-m", "fastchat.serve.gradio_web_server_multi", "--host", "0.0.0.0", "--port", "8080", "--controller-url", !Sub "http://${ControllerLoadBalancerDNSName}"]

  ### Service ###
  ControllerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref ControllerTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ControllerSGID
          Subnets:
            - !Ref PrivateSubnetID
            - !Ref PrivateSubnet2ID
      LoadBalancers:
        - ContainerName: fastchat-controller
          ContainerPort: 3000
          TargetGroupArn: !Ref ControllerTargetGroupArn

  GradioService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref GradioTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref GradioSGID
          Subnets:
            - !Ref PrivateSubnetID
            - !Ref PrivateSubnet2ID
      LoadBalancers:
        - ContainerName: fastchat-gradio
          ContainerPort: 8080
          TargetGroupArn: !Ref GradioTargetGroupArn
