AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for FastChat Controller

Parameters:
  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet
  ControllerSGID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Controller Security Group
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the Key Pair

Resources:
  ControllerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref ControllerSGID
      SubnetId: !Ref PrivateSubnetID
      ImageId: ami-01bef798938b7644d  # Ubuntu Server 24.04 LTS
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 64
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: !Sub "controller-${AWS::StackName}"
      # TODO: インストール, 起動スクリプトをよりシンプルに管理したい
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          apt-get -y update
          apt-get -y install python3-pip python3-venv
          python3 -m venv /opt/fschat-env
          source /opt/fschat-env/bin/activate
          pip install fschat
          
          mkdir -p /var/log/fschat
          chmod 755 /var/log/fschat
          
          cat << EOF > /etc/systemd/system/fschat-controller.service
          [Unit]
          Description=FastChat Controller
          After=network.target
          [Service]
          ExecStart=/opt/fschat-env/bin/python -m fastchat.serve.controller --host 0.0.0.0 --port 3000
          Restart=always
          WorkingDirectory=/var/log/fschat
          [Install]
          WantedBy=multi-user.target
          EOF
          
          systemctl daemon-reload
          systemctl enable fschat-controller
          systemctl start fschat-controller

Outputs:
  ControllerIP:
    Description: Controller IP Address
    Value: !GetAtt ControllerInstance.PrivateIp
