AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for FastChat Controller

Parameters:
  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet
  ControllerSGID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Controller Security Group
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the Key Pair
  FastChatECRRepositoryName:
    Type: String
    Description: ECR Repository name for FastChat
  ECSCluster:
    Type: String
    Description: The ID of the ECS Cluster
  ECSLogGroup:
    Type: String
    Description: The name of the ECS Log Group

Resources:
  ControllerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Cpu: 2048 # 2 vCPU
      Memory: 4096 # 4GB
      NetworkMode: awsvpc

Outputs:
  ControllerIP:
    Description: Controller IP Address
    Value: !GetAtt ControllerInstance.PrivateIp
