AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Public Subnet
  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Public Subnet 2
  GradioALBSGId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Gradio ALB Security Group

Resources:
  GradioALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ['-', ['gradio-alb', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      Subnets:
        - !Ref PublicSubnetId
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref GradioALBSGId
      Scheme: internet-facing

  GradioTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join ['-', ['gradio-tg', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /

  GradioListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GradioTargetGroup
      LoadBalancerArn: !Ref GradioALB
      Port: 80
      Protocol: HTTP

Outputs:
  GradioALBId:
    Description: Application Load Balancer ID for Gradio
    Value: !Ref GradioALB
  GradioTargetGroupArn:
    Description: Target Group ARN for Gradio
    Value: !Ref GradioTargetGroup