AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC
  PublicSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Public Subnet
  PublicSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Public Subnet 2
  PrivateSubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet 2
  ControllerALBSGID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Controller ALB Security Group
  GradioALBSGID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Gradio ALB Security Group

Resources:
  ### Target Group ###
  ControllerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPCID
      HealthCheckPath: /test_connection
      Tags:
        - Key: Name
          Value: !Sub "controller-tg-${AWS::StackName}"

  GradioTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub "gradio-tg-${AWS::StackName}"

  ### Load Balancer ###
  ControllerLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Subnets:
        - !Ref PrivateSubnetID
        - !Ref PrivateSubnet2ID
      SecurityGroups:
        - !Ref ControllerALBSGID
      Tags:
        - Key: Name
          Value: !Sub "controller-lb-${AWS::StackName}"

  GradioLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnetID
        - !Ref PublicSubnet2ID
      SecurityGroups:
        - !Ref GradioALBSGID
      Tags:
        - Key: Name
          Value: !Sub "gradio-lb-${AWS::StackName}"

  ### Listener ###
  ControllerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ControllerTargetGroup
      LoadBalancerArn: !Ref ControllerLoadBalancer
      Port: 80
      Protocol: HTTP

  GradioListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GradioTargetGroup
      LoadBalancerArn: !Ref GradioLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  ControllerLoadBalancerDNSName:
    Description: DNS Name of the Controller Load Balancer
    Value: !GetAtt ControllerLoadBalancer.DNSName
  GradioLoadBalancerDNSName:
    Description: DNS Name of the Gradio Load Balancer
    Value: !GetAtt GradioLoadBalancer.DNSName
  ControllerTargetGroupArn:
    Description: ARN of the Controller Target Group
    Value: !Ref ControllerTargetGroup
  GradioTargetGroupArn:
    Description: ARN of the Gradio Target Group
    Value: !Ref GradioTargetGroup