AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ModelSGId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Model Security Group
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Subnet
  NeuronAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/neuron/dlami/multi-framework/ubuntu-22.04/latest/image_id
    Description: The Neuron AMI
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The EC2 Key Pair to allow SSH access to the instances
  # for API Gateway
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC
  ModelNLBSGId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Model NLB Security Group
  NLBSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet 1
  NLBSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Private Subnet 2

# Fn::ForEach では TemplateURL が展開されなかったため、個別に定義
Resources:
  ModelInstance2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !Ref ModelSGId
        SubnetId: !Ref SubnetId
        ImageId: !Ref NeuronAMI
        KeyName: !Ref KeyName
        InstanceType: inf2.24xlarge
        BlockDeviceName: "/dev/sda1"
        VolumeSize: 512
        VolumeType: gp3
        TagName: model-2
        VpcId: !Ref VpcId
        NLBSGId: !Ref ModelNLBSGId
        NLBSubnet1Id: !Ref NLBSubnet1Id
        NLBSubnet2Id: !Ref NLBSubnet2Id

  ModelInstance3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !Ref ModelSGId
        SubnetId: !Ref SubnetId
        ImageId: !Ref NeuronAMI
        KeyName: !Ref KeyName
        InstanceType: inf2.24xlarge
        BlockDeviceName: "/dev/sda1"
        VolumeSize: 512
        VolumeType: gp3
        TagName: model-3
        VpcId: !Ref VpcId
        NLBSGId: !Ref ModelNLBSGId
        NLBSubnet1Id: !Ref NLBSubnet1Id
        NLBSubnet2Id: !Ref NLBSubnet2Id

  ModelInstance4:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !Ref ModelSGId
        SubnetId: !Ref SubnetId
        ImageId: !Ref NeuronAMI
        KeyName: !Ref KeyName
        InstanceType: inf2.48xlarge
        BlockDeviceName: "/dev/sda1"
        VolumeSize: 512
        VolumeType: gp3
        TagName: model-4
        VpcId: !Ref VpcId
        NLBSGId: !Ref ModelNLBSGId
        NLBSubnet1Id: !Ref NLBSubnet1Id
        NLBSubnet2Id: !Ref NLBSubnet2Id
