AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ModelSGId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Model Security Group
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the Subnet
  NeuronAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/neuron/dlami/multi-framework/ubuntu-22.04/latest/image_id
    Description: The Neuron AMI

# Fn::ForEach では TemplateURL が展開されなかったため、個別に定義
Resources:
  ModelInstance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !Ref ModelSGId
        SubnetId: !Ref SubnetId
        ImageId: !Ref NeuronAMI
        InstanceType: inf2.24xlarge
        BlockDeviceName: "/dev/sda1"
        VolumeSize: 512
        VolumeType: gp3
        TagName: !Sub "model-1"