AWSTemplateFormatVersion: '2010-09-09'
Description: Chatbot Arena Infrastructure
Transform: AWS::LanguageExtensions

Parameters:
  AmazonLinux2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: The Amazon Linux 2 AMI

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security-group.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  ControllerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !GetAtt SecurityGroupStack.Outputs.ControllerSGId
        SubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        ImageId: !Ref AmazonLinux2AMI
        InstanceType: t2.medium
        BlockDeviceName: "/dev/xvda"
        VolumeSize: 64
        VolumeType: gp2
        TagName: "controller"

  GradioStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !GetAtt SecurityGroupStack.Outputs.GradioSGId
        SubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        ImageId: !Ref AmazonLinux2AMI
        InstanceType: t2.medium
        BlockDeviceName: "/dev/xvda"
        VolumeSize: 64
        VolumeType: gp2
        TagName: "gradio"

  ModelInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./model-instances.yaml
      Parameters:
        ModelSGId: !GetAtt SecurityGroupStack.Outputs.ModelSGId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./load-balancer.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        GradioALBSGId: !GetAtt SecurityGroupStack.Outputs.GradioALBSGId
