AWSTemplateFormatVersion: "2010-09-09"
Description: Chatbot Arena Infrastructure
Transform: AWS::LanguageExtensions

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The EC2 Key Pair to allow SSH access to the instances

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security-group.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  FastChatStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !GetAtt SecurityGroupStack.Outputs.FastChatSGId
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        KeyName: !Ref KeyName
        InstanceType: t3.large
        BlockDeviceName: /dev/xvda
        VolumeSize: 128
        VolumeType: gp2
        TagName: fastchat

  FastChatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !GetAtt FastChatStack.Outputs.InstanceId

  ModelInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./model-instances.yaml
      Parameters:
        ModelSGId: !GetAtt SecurityGroupStack.Outputs.ModelSGId
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        KeyName: !Ref KeyName
