AWSTemplateFormatVersion: "2010-09-09"
Description: Chatbot Arena Infrastructure
Transform: AWS::LanguageExtensions

Parameters:
  AmazonLinux2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: The Amazon Linux 2 AMI
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The EC2 Key Pair to allow SSH access to the instances

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security-group.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  FastChatStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !GetAtt SecurityGroupStack.Outputs.FastChatSGId
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        ImageId: !Ref AmazonLinux2AMI
        KeyName: !Ref KeyName
        InstanceType: t2.large
        BlockDeviceName: /dev/xvda
        VolumeSize: 64
        VolumeType: gp2
        TagName: fastchat

  ModelInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./model-instances.yaml
      Parameters:
        ModelSGId: !GetAtt SecurityGroupStack.Outputs.ModelSGId
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        KeyName: !Ref KeyName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ModelNLBSGId: !GetAtt SecurityGroupStack.Outputs.ModelNLBSGId
        NLBSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnetId
        NLBSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  FastChatALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./fastchat-alb.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        FastChatALBSGId: !GetAtt SecurityGroupStack.Outputs.FastChatALBSGId
        FastChatInstanceId: !GetAtt FastChatStack.Outputs.InstanceId
