AWSTemplateFormatVersion: '2010-09-09'
Description: Chatbot Arena Infrastructure

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security-group.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  ControllerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./controller.yaml
      Parameters:
        ControllerSGId: !GetAtt SecurityGroupStack.Outputs.ControllerSGId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId

  GradioStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./gradio.yaml
      Parameters:
        GradioSGId: !GetAtt SecurityGroupStack.Outputs.GradioSGId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./load-balancer.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        GradioALBSGId: !GetAtt SecurityGroupStack.Outputs.GradioALBSGId
