AWSTemplateFormatVersion: "2010-09-09"
Description: Chatbot Arena Infrastructure
Transform: AWS::LanguageExtensions

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The EC2 Key Pair to allow SSH access to the instances
  FastChatBaseImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
    Description: The base AMI ID for FastChat instances

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security-group.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  FastChatStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./instance.yaml
      Parameters:
        SGId: !GetAtt SecurityGroupStack.Outputs.FastChatSGId
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        KeyName: !Ref KeyName
        InstanceType: t3.large
        ImageId: !Ref FastChatBaseImageId
        BlockDeviceName: /dev/sda1
        VolumeSize: 128
        VolumeType: gp3
        TagName: fastchat

  FastChatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !GetAtt FastChatStack.Outputs.InstanceId

  ModelInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./model-instances.yaml
      Parameters:
        ModelSGId: !GetAtt SecurityGroupStack.Outputs.ModelSGId
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        KeyName: !Ref KeyName
