AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC

Resources:
  ### Security Group ###
  FastChatSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "fastchat-sg-${AWS::StackName}"
      GroupDescription: Allow traffic for FastChat
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref FastChatALBSG

  ModelSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "model-sg-${AWS::StackName}"
      GroupDescription: Allow traffic for Model
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3999
          SourceSecurityGroupId: !Ref FastChatSG 
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3999
          SourceSecurityGroupId: !Ref ModelNLBSG
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  FastChatALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "fastchat-alb-sg-${AWS::StackName}"
      GroupDescription: Allow traffic for FastChat ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ModelNLBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "model-nlb-sg-${AWS::StackName}"
      GroupDescription: Allow traffic for Model NLB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  FastChatSGId:
    Description: Security Group ID for FastChat
    Value: !Ref FastChatSG
  FastChatALBSGId:
    Description: Security Group ID for FastChat ALB
    Value: !Ref FastChatALBSG
  ModelSGId:
    Description: Security Group ID for Model
    Value: !Ref ModelSG
  ModelNLBSGId:
    Description: Security Group ID for Model NLB
    Value: !Ref ModelNLBSG