x-devices: &devices
  - /dev/neuron0
  - /dev/neuron1
  - /dev/neuron2
  - /dev/neuron3
  - /dev/neuron4
  - /dev/neuron5

services:
  model-1:
    container_name: vllm-openai-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    ipc: host
    volumes:
      - ./chat_template:/app/chat_template
      - ~/.cache/huggingface:/root/.cache/huggingface
      - neuron_compile_cache:/var/tmp/neuron-compile-cache
    env_file:
      - .env
    devices: *devices
    environment:
      TZ: "Asia/Tokyo"
      MODEL: meta-llama/Meta-Llama-3-8B
      PORT: 3000
      CORES: 0-1

volumes:
  neuron_compile_cache: