name: Build And Push

on:
  push:
    tags:
      - 'vllm-*'

env:
  AWS_REGION: ap-northeast-1
  ECR_REGISTRY: 179859975125.dkr.ecr.ap-northeast-1.amazonaws.com
jobs:
  build:
    name: Build And Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_REGISTRY }}
      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: docker/vllm
          push: true
          provenance: false
          tags: ${{ env.ECR_REGISTRY }}/vllm:latest